language: node_js
node_js:
  - "8.9.4"
cache:
  directories:
    - node_modules
install:
  - yarn
  - yarn generate
deploy: 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  target_branch: master
  on:
    branch: dev